# SPDX-License-Identifier: GPL-2.0-or-later
"""Actual built artifact/PIC/ABI/signature/metadata and native relocation audit."""
import json
import os
from pathlib import Path
import re
import shutil
import tempfile
from io_utils import BASE, HERE, sha, repo_file, write_json
from source_tree import verify_tree

BINARIES = ['native_probe','eigen_acceptance','embree_acceptance','ceres_acceptance',
            'logging_acceptance','pic_acceptance','libcore_pic_bridge.so']


def normalize_metadata(prefix, root):
    journal = root / 'metadata-normalization.json'
    records = json.loads(journal.read_text())['changes'] if journal.exists() else []
    for file in sorted(prefix.rglob('*.pc')):
        before = file.read_bytes()
        text = before.decode()
        if str(prefix) not in text:
            continue
        relative = file.relative_to(prefix)
        original = root / 'metadata-original' / sha(file) / relative
        original.parent.mkdir(parents=True,exist_ok=True)
        if original.exists() and original.read_bytes() != before:
            raise ValueError('Original generated metadata snapshot changed')
        if not original.exists():
            original.write_bytes(before)
        output = []
        seen = False
        for line in text.splitlines():
            if line.startswith('prefix='):
                line = 'prefix=${pcfiledir}/' + os.path.relpath(prefix,file.parent)
                seen = True
            else:
                line = line.replace(str(prefix),'${prefix}')
            output.append(line)
        if not seen:
            output.insert(0,'prefix=${pcfiledir}/' + os.path.relpath(prefix,file.parent))
        file.write_text('\n'.join(output) + '\n')
        records.append({'path':str(relative),'before_snapshot':str(original),'after_sha256':sha(file)})
    write_json(root / 'metadata-normalization.json',{'scope':'Caller-owned prefix PCs only; preserve original generated bytes','changes':records})


def install_notices(prefix):
    sources = json.loads((BASE / 'provenance.json').read_text())['sources'] + [json.loads((HERE / 'inputs.lock.json').read_text())['tbb_source']]
    for dep in sources:
        for notice in dep['notices']:
            target = prefix / 'share/licenses/core-deps' / dep['name'] / notice['source_path']
            target.parent.mkdir(parents=True,exist_ok=True)
            original = repo_file(notice['mirror'])
            if target.exists() and sha(target) != notice['sha256']:
                raise ValueError('Conflicting installed original notice')
            if not target.exists():
                shutil.copyfile(original,target)


def artifacts(args, root, runner):
    prefix = args.prefix
    for name in ['embree4','sys','math','simd','lexers','tasking','ceres','gflags','glog']:
        if not (prefix / 'lib' / ('lib' + name + '.a')).is_file():
            raise ValueError('Real installed core archive absent: ' + name)
    if not list((prefix / 'lib').glob('libabsl_*.a')):
        raise ValueError('Real Abseil closure archives absent')
    rows = []
    for archive in sorted((prefix / 'lib').glob('*.a')):
        headers = runner.run([args.sdk_root / 'llvm/bin/llvm-readelf','-h',archive],'artifact-headers-' + archive.stem)
        machines = re.findall(r'Machine:\s+([^\n]+)',headers)
        if not machines or any(m.strip() != 'AArch64' for m in machines):
            raise ValueError('Actual archive member architecture mismatch')
        symbols = runner.run([args.sdk_root / 'llvm/bin/llvm-nm','--undefined-only','--demangle',archive],
                             'artifact-symbols-' + archive.stem)
        if 'std::__h::' in symbols or re.search(r'\bpthread_cancel\b',symbols):
            raise ValueError('Wrong stdlib ABI or unavailable cancellation dependency')
        rows.append({'path':str(archive),'sha256':sha(archive),'members':len(machines)})
    compile_rows = []
    sources = []
    for name in ['eigen','embree','abseil','ceres','gflags','glog']:
        sources.append(verify_tree(root / 'sources' / name,name,patched=True,allow_generated=True))
        if name == 'eigen':
            continue
        database = root / 'build' / name / 'compile_commands.json'
        entries = json.loads(database.read_text())
        if not entries or any('-fPIC' not in x['command'] or re.search(r'\s-m(?:sse|avx)',x['command']) for x in entries):
            raise ValueError('Actual native PIC/ISA compile evidence mismatch')
        compile_rows.append({'name':name,'units':len(entries),'sha256':sha(database)})
    binaries = []
    for name in BINARIES:
        file = root / 'build/acceptance' / name
        sections = runner.run([args.sdk_root / 'llvm/bin/llvm-readelf','-S',file],'artifact-elf-sections-' + name)
        dynamic = runner.run([args.sdk_root / 'llvm/bin/llvm-readelf','-d',file],'artifact-elf-dynamic-' + name)
        needed = re.findall(r'\(NEEDED\).*?\[([^\]]+)\]',dynamic)
        if '.codesign' not in sections or any('libc++' in n for n in needed):
            raise ValueError('Unsigned ELF or undeclared dynamic C++ runtime')
        binaries.append({'name':name,'sha256':sha(file),'needed':needed,'codesign':True})
    metadata = []
    for file in prefix.rglob('*'):
        if file.is_file() and file.suffix in ('.cmake','.pc'):
            text = file.read_text()
            if any(p in text for p in [str(root / 'sources'),str(root / 'build'),str(prefix)]):
                raise ValueError('Installed metadata leaks source/build/original prefix: ' + str(file))
            metadata.append({'path':str(file.relative_to(prefix)),'sha256':sha(file)})
    for dep in json.loads((BASE / 'provenance.json').read_text())['sources']:
        for notice in dep['notices']:
            file = prefix / 'share/licenses/core-deps' / dep['name'] / notice['source_path']
            if not file.is_file() or sha(file) != notice['sha256']:
                raise ValueError('Original installed core notice missing/changed')
    result = {'result':'PASS actual artifacts within declared core scope','archives':rows,'compile':compile_rows,
              'binaries':binaries,'metadata':metadata,'source_integrity':sources}
    write_json(root / 'artifacts.json',result)
    return result


def migrate(args, root, runner, consume):
    with tempfile.TemporaryDirectory(prefix='core-native-migrate-',dir=runner.tmp) as td:
        moved = Path(td) / 'native core moved with spaces'
        core = moved / 'core prefix'
        tbb = moved / 'declared TBB prefix'
        shutil.copytree(args.prefix,core,symlinks=True)
        shutil.copytree(args.tbb_prefix,tbb,symlinks=True)
        preserved = 0
        for source_prefix,destination in [(args.prefix,core),(args.tbb_prefix,tbb)]:
            for file in source_prefix.rglob('*'):
                if file.is_file() and not file.is_symlink():
                    if sha(file) != sha(destination / file.relative_to(source_prefix)):
                        raise ValueError('Moved prefix bytes differ')
                    preserved += 1
        consume(moved / 'fresh consumer build',core,tbb,'migration',forbidden=[str(args.prefix),str(args.tbb_prefix)])
        result = {'result':'PASS actual fresh moved native links and tests','preserved_files':preserved,
                  'moved_root_contains_spaces':True,'sdk_compiler':'Declared read-only development prerequisites',
                  'tbb_scope':'Only caller-selected actual TBB closure consumed; other files in that prefix are not separately promised'}
    result['temporary_tree_cleaned'] = True
    write_json(root / 'migration.json',result)
    return result
