# SPDX-License-Identifier: GPL-2.0-or-later
"""Clear known tool injection variables; reject unclassified ambient selectors."""
import os
KNOWN={'CC','CXX','CFLAGS','CXXFLAGS','CPPFLAGS','LDFLAGS','LIBRARY_PATH','LD_LIBRARY_PATH','LD_PRELOAD','CPATH','C_INCLUDE_PATH','CPLUS_INCLUDE_PATH','OBJC_INCLUDE_PATH','COMPILER_PATH','GCC_EXEC_PREFIX','SDKROOT','CCC_OVERRIDE_OPTIONS','CLANG_CONFIG_FILE_SYSTEM_DIR','CLANG_CONFIG_FILE_USER_DIR','CMAKE_PREFIX_PATH','CMAKE_MODULE_PATH','CMAKE_TOOLCHAIN_FILE','CMAKE_GENERATOR','CMAKE_BUILD_PARALLEL_LEVEL','CMAKE_PROJECT_INCLUDE','CMAKE_PROJECT_TOP_LEVEL_INCLUDES','PKG_CONFIG_PATH','PKG_CONFIG_LIBDIR','PKG_CONFIG_SYSROOT_DIR','PYTHONPATH','PYTHONHOME','MAKEFLAGS','MFLAGS','NINJAFLAGS','MESON_ARGS','MESON_CROSS_FILE','MESON_NATIVE_FILE'}
KNOWN.update({'GIT_DIR','GIT_WORK_TREE','GIT_COMMON_DIR','GIT_INDEX_FILE','GIT_OBJECT_DIRECTORY','GIT_ALTERNATE_OBJECT_DIRECTORIES','GIT_CONFIG_COUNT','GIT_CONFIG_SYSTEM','GIT_CONFIG_GLOBAL','GIT_CONFIG_NOSYSTEM','GIT_CONFIG','GIT_CONFIG_PARAMETERS','GIT_PREFIX','GIT_CEILING_DIRECTORIES'})
PREFIXES=('CMAKE_','CLANG_CONFIG_','PKG_CONFIG_','MESON_','GIT_CONFIG_KEY_','GIT_CONFIG_VALUE_')

def clean(environment=None,tmp_dir=None):
    env=dict(os.environ if environment is None else environment)
    unknown=[k for k,v in env.items() if v and k.startswith(PREFIXES) and k not in KNOWN]
    if unknown:raise ValueError('Unknown ambient build selectors: '+','.join(sorted(unknown)))
    removed=sorted(k for k in KNOWN if k in env)
    for key in KNOWN:env.pop(key,None)
    env.update(PYTHONDONTWRITEBYTECODE='1',SOURCE_DATE_EPOCH='1767225600',TZ='UTC',GIT_CONFIG_NOSYSTEM='1',GIT_CONFIG_GLOBAL='/dev/null')
    if tmp_dir:env['TMPDIR']=str(tmp_dir)
    return env,removed
