# SPDX-License-Identifier: GPL-2.0-or-later
# Observe the actual imported static interfaces after formal Blender configuration.
# This hook does not override package targets, native checks, or feature options.
include_guard(GLOBAL)

function(_ohos_editor_json_string output value)
  string(REPLACE "\\" "\\\\" value "${value}")
  string(REPLACE "\"" "\\\"" value "${value}")
  string(REPLACE "\n" "\\n" value "${value}")
  string(REPLACE "\r" "\\r" value "${value}")
  string(REPLACE "\t" "\\t" value "${value}")
  set(${output} "\"${value}\"" PARENT_SCOPE)
endfunction()

function(_ohos_editor_json_array output)
  set(_result "[")
  set(_separator "")
  foreach(_value IN LISTS ARGN)
    _ohos_editor_json_string(_quoted "${_value}")
    string(APPEND _result "${_separator}${_quoted}")
    set(_separator ",")
  endforeach()
  string(APPEND _result "]")
  set(${output} "${_result}" PARENT_SCOPE)
endfunction()

function(_ohos_editor_observe_imports)
  get_property(_targets DIRECTORY "${CMAKE_SOURCE_DIR}" PROPERTY IMPORTED_TARGETS)
  list(APPEND _targets ${OHOS_EDITOR_REQUIRED_IMPORTED_TARGETS})
  list(REMOVE_DUPLICATES _targets)
  # Imported interface dependencies may be aliases absent from IMPORTED_TARGETS.
  set(_scan ${_targets})
  foreach(_iteration RANGE 0 16)
    set(_next "")
    foreach(_target IN LISTS _scan)
      if(NOT TARGET "${_target}")
        message(FATAL_ERROR "Declared editor imported target is absent: ${_target}")
      endif()
      get_target_property(_links "${_target}" INTERFACE_LINK_LIBRARIES)
      if(_links AND NOT _links MATCHES "-NOTFOUND$")
        foreach(_link IN LISTS _links)
          if(TARGET "${_link}" AND NOT _link IN_LIST _targets)
            list(APPEND _targets "${_link}")
            list(APPEND _next "${_link}")
          endif()
        endforeach()
      endif()
    endforeach()
    if(NOT _next)
      break()
    endif()
    set(_scan ${_next})
  endforeach()
  if(_next)
    message(FATAL_ERROR "Editor imported interface recursion exceeded fixed bound")
  endif()
  list(SORT _targets)
  set(_json "{\"schema\":1,\"targets\":[")
  set(_separator "")
  foreach(_target IN LISTS _targets)
    get_target_property(_type "${_target}" TYPE)
    _ohos_editor_json_string(_name "${_target}")
    _ohos_editor_json_string(_type_json "${_type}")
    set(_locations "")
    foreach(_property IMPORTED_LOCATION IMPORTED_LOCATION_RELEASE IMPORTED_LOCATION_DEBUG
                      IMPORTED_LOCATION_RELWITHDEBINFO IMPORTED_LOCATION_MINSIZEREL
                      IMPORTED_LOCATION_NOCONFIG)
      get_target_property(_value "${_target}" "${_property}")
      if(_value AND NOT _value MATCHES "-NOTFOUND$")
        list(APPEND _locations "${_value}")
      endif()
    endforeach()
    list(REMOVE_DUPLICATES _locations)
    _ohos_editor_json_array(_locations_json ${_locations})
    string(APPEND _json "${_separator}{\"name\":${_name},\"type\":${_type_json},\"imported_locations\":${_locations_json}")
    foreach(_pair "include_dirs|INTERFACE_INCLUDE_DIRECTORIES"
                  "link_libraries|INTERFACE_LINK_LIBRARIES"
                  "link_options|INTERFACE_LINK_OPTIONS"
                  "compile_definitions|INTERFACE_COMPILE_DEFINITIONS")
      string(REPLACE "|" ";" _parts "${_pair}")
      list(GET _parts 0 _field)
      list(GET _parts 1 _property)
      get_target_property(_values "${_target}" "${_property}")
      if(NOT _values OR _values MATCHES "-NOTFOUND$")
        set(_values "")
      endif()
      _ohos_editor_json_array(_array ${_values})
      string(APPEND _json ",\"${_field}\":${_array}")
    endforeach()
    string(APPEND _json "}")
    set(_separator ",")
  endforeach()
  string(APPEND _json "]}\n")
  file(WRITE "${CMAKE_BINARY_DIR}/editor-imports.json" "${_json}")
endfunction()

cmake_language(DEFER DIRECTORY "${CMAKE_SOURCE_DIR}" CALL _ohos_editor_observe_imports)
