#!/usr/bin/env python3
"""Native compiler driver: preserve compiler identity; sign every linked ELF.
Use cache-resident executable sh launchers generated by native_llvm.py.
No stripping after signing. No forced CMake probe success or compiler version.
"""
import os
from pathlib import Path
import shlex
import shutil
import subprocess
import sys
import tempfile


def expand_for_inspection(args, depth=0):
    if depth > 4:
        raise SystemExit('Response file nesting too deep')
    result = []
    for arg in args:
        if arg.startswith('@') and Path(arg[1:]).is_file():
            result.extend(expand_for_inspection(shlex.split(Path(arg[1:]).read_text()),depth + 1))
        else:
            result.append(arg)
    return result


def main():
    if '--' not in sys.argv:
        raise SystemExit('Usage: python3 sign_compiler.py REAL_COMPILER [DEFAULT_FLAGS...] -- [COMPILER_ARGS...]')
    separator = sys.argv.index('--')
    command = sys.argv[1:separator]
    args = sys.argv[separator + 1:]
    if not command:
        raise SystemExit('Missing real compiler')
    inspected = expand_for_inspection(args)
    nonlink = {'-c','-E','-S','-M','-MM','-fsyntax-only','-###','--version','--help','-cc1','-cc1as'}
    link = not any(a in nonlink or a.startswith(('-dump','-print','--print')) for a in inspected)
    output = Path('a.out')
    for i, arg in enumerate(inspected):
        if arg == '-o' and i + 1 < len(inspected):
            output = Path(inspected[i + 1])
        elif arg.startswith('-o') and len(arg) > 2:
            output = Path(arg[2:])
    # A query without an input never touches a preexisting a.out.
    input_present = '-' in inspected or any(not a.startswith('-') and Path(a).is_file() and a != str(output) for a in inspected)
    library_link = any(a=='-l' or a.startswith('-l') and len(a)>2 or a=='-shared' or a.startswith('-Wl,-l') for a in inspected)
    link_candidate = link
    forwarded_input = any(Path(piece).is_file() for arg in inspected if arg.startswith('-Wl,') for piece in arg[4:].split(',') if piece and not piece.startswith('-'))
    link = link_candidate and (input_present or library_link or forwarded_input)
    previous_output = output.stat() if output.is_file() else None
    if link:
        output.unlink(missing_ok=True)
    else:
        # Remove only launcher-injected LINK defaults for compile-only/query calls.
        # Otherwise CheckCompilerFlag treats unused -fuse-ld/-static-libstdc++ as
        # false negatives (e.g. genuine -fPIC support). User probe flags stay intact.
        command = [command[0], *[a for a in command[1:] if not
                   (a == '-static-libstdc++' or a == '-lc++experimental' or
                    a.startswith(('-fuse-ld=', '--ld-path=', '-Wl,', '-L')))]]
    # CPython's patched configure/Makefile select the true unversioned SONAME before linking.
    # Do not inject a self-dependency while linking libpython itself.
    run = subprocess.run(command + args)
    if run.returncode:
        raise SystemExit(run.returncode)
    if not link_candidate or not output.is_file():
        return
    if not link:
        current = output.stat()
        if previous_output is not None and (current.st_ino,current.st_size,current.st_mtime_ns)==(previous_output.st_ino,previous_output.st_size,previous_output.st_mtime_ns):
            return # a real no-input query must not touch a preexisting output
    if output.is_symlink():raise SystemExit('Linked output symlink refused')
    with output.open('rb') as f:
        header=f.read(18)
        if header[:4] != b'\x7fELF' or header[5:6]!=b'\x01' or int.from_bytes(header[16:18],'little') not in (2,3):
            return # relocatable objects/PCH are not executable/shared link outputs
    signer = os.environ.get('OHOS_BINARY_SIGN_TOOL')
    if not signer or not Path(signer).is_absolute() or not Path(signer).is_file():
        raise SystemExit('Explicit pinned OHOS_BINARY_SIGN_TOOL required')
    with tempfile.TemporaryDirectory(prefix='llvm-link-sign-', dir=os.environ['TMPDIR']) as temp:
        signed = Path(temp) / 'signed'
        tool_env = os.environ.copy()
        # Signer is a system std::__h executable; application SDK std::__n1 paths
        # (and its libc++.so linker script) must not shadow the signer runtime.
        tool_env.pop('LD_LIBRARY_PATH', None)
        tool_env.pop('LD_PRELOAD', None)
        process = subprocess.run([signer, 'sign', '-inFile', str(output), '-outFile', str(signed), '-selfSign', '1'],
                                 env=tool_env, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        if process.returncode != 0 or not signed.is_file():
            print(process.stdout, file=sys.stderr)
            raise SystemExit('Signing failed or signed file absent')
        # Some signer invalid commands exit 0: verify codesign section before replacing ELF.
        readelf = os.environ.get('OHOS_LLVM_READELF')
        if not readelf or not Path(readelf).is_absolute() or not Path(readelf).is_file():
            raise SystemExit('Explicit pinned OHOS_LLVM_READELF required')
        sections = subprocess.check_output([readelf, '--sections', str(signed)], env=tool_env, text=True)
        if '.codesign' not in sections:
            raise SystemExit('Signed output lacks .codesign section')
        signed.chmod(0o755)
        output.unlink()
        shutil.move(str(signed), output)


if __name__ == '__main__':
    main()
